name: Tag Issues and Pull Requests

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  tag-issues:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Build and run C# program
        run: dotnet run --project "./auto-tag/UnityFlow.AutoTag/UnityFlow.AutoTag.csproj"
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.UNITYFLOW_SECRET }}