name: Auto-Tag Issues and Pull Requests

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto-tag issue or pull request
        env:
          UNITYFLOW_SECRET: ${{ secrets.UNITYFLOW_SECRET }}
        run: |
          cd auto-tag && \
          npm install && \
          npm run start

